name: Node.js CI

on:
  push:
    branches: [ "flavour" ]
  pull_request:
    branches: [ "flavour" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
    - run: npm install
    - run: pm2 restart app-name
